version: '3'
services:
  web:
    build: .
    container_name: roomz_api
    ports:
      - "8000:80"
    env_file: .test_env
    depends_on:
      - roomz_db
    volumes:
      - ./app:/code/app
  roomz_db:
    image: postgres:latest
    container_name: roomz_postgres
    ports:
      - "5432:5432"
    env_file: .test_env